@startuml ДиаграммаПользователиИБизнесПроцессы

package "Административные пользователи" {
    actor "Учителя" as t
    actor "Администраторы" as a
}

package "Обычные пользователи" {
    actor "Родители" as p
    actor "Студенты" as s
}

package "Бизнес-процессы" {
    usecase "Управление оценок" as BP1
    usecase "Просмотр оценок" as BP2
    usecase "Учёт списков пользователей" as BP3
    usecase "Поиск нужных пользователей" as BP4
    usecase "Добавление авторизации пользователей" as BP5
}

t --> BP1
t --> BP2
t --> BP3
t --> BP4
t --> BP5

a --> BP1
a --> BP2
a --> BP3
a --> BP4
a --> BP5

p --> BP2

s --> BP2

@enduml
